services:
  - type: web
    name: job-order-queue
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t job-order-queue .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
